module.exports = {
  apps: [
    {
      name: 'app1',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 4000,
        DB_HOST: '192.168.1.50',
        DB_PORT: 5432,
        DB_USER: 'postgres',
        DB_PASS: 'fadhil',
        DB_DIALECT: 'postgres',
        DB_NAME: 'projek',
        JWTKEY: 'random_secret_key',
        TOKEN_EXPIRATION: '1h',
        BEARER: 'Bearer',
      },
    },
    {
      name: 'app2',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 4001,
        DB_HOST: '192.168.1.50',
        DB_PORT: 5432,
        DB_USER: 'postgres',
        DB_PASS: 'fadhil',
        DB_DIALECT: 'postgres',
        DB_NAME: 'projek',
        JWTKEY: 'random_secret_key',
        TOKEN_EXPIRATION: '1h',
        BEARER: 'Bearer',
      },
    },
  ],
};
